# This workflow releases the `matrix-sdk-crypto-wasm` project.
#
# It is triggered when a new tag appears that matches
# `v[0-9]+.*`. This workflow builds the package
# for the bindings, runs its tests to ensure everything is still
# correct, and publishes the package on NPM and on a newly created
# Github release.


name: Release `crypto-js`

env:
  CARGO_TERM_COLOR: always

on:
  push:
    tags:
      - v[0-9]+.*

jobs:
  publish-matrix-sdk-crypto-wasm:
    name: Publish ðŸ•¸ [m]-crypto-wasm
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

        # Keep this in sync with:
        # .github/workflows/ci.yml
        # .github/workflows/latest-matrix-sdk-crypto.yml
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.0

      - name: Install NPM dependencies
        run: npm install

      - name: Publish the WebAssembly + JavaScript binding (imply building + testing)
        uses: JS-DevTools/npm-publish@v1
        with:
          package: package.json
          access: public
          token: ${{ secrets.NPM_TOKEN }}

  github-release:
    name: Create the Github release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Create the Github release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
